#!/bin/sh

ctags -R --c++-kinds=+p --fields=+iaS --extra=+q --exclude=.svn --exclude=.git
find . -name "*.h" -o -name "*.c" -o -name "*.cpp" -o -name "*.s" -o -name "*.S" > cscope.files
cscope -Rbkq -i cscope.files
